---
- hosts: "{{ openshift_node }}"
  gather_facts: False

  tasks:
    - name: Login as system:admin
      command: oc login -u system:admin

    - name: Add cluster-admin role to user
      command: oc adm policy add-cluster-role-to-user cluster-admin admin

    - name: Login as admin
      command: oc login -u admin -p admin