---
- hosts: "{{ openshift_node }}"
  gather_facts: False

  roles:
    #- { role: 'config_dns', tags: 'config_dns' }
    #- { role: 'post_install', tags: 'post_install'}
    - { role: 'persistence', tags: 'persistence'}
    #- { role: 'install_nexus', tags: 'install_nexus'}
    #- { role: 'install_jenkins', tags: 'install_jenkins'}